# Generated by Django 4.0.6 on 2022-12-26 22:09

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default.webp', upload_to=users.models.upload_to),
        ),
    ]
